language: script

env:
  global:
     CF_TARGET_URL="https://api.ng.bluemix.net"

services:
  - docker

script:
- bash -n $(find . -name *.sh)
- ./.verify-links.sh -v

deploy:
  - provider: script
    skip_cleanup: true
    script: echo workshop/deploy_rollup.sh
    on:
      all_branches: true
